"""add xp_score duration tags to event

Revision ID: 13470ef2b13c
Revises: 
Create Date: 2026-03-27 09:25:10.903701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13470ef2b13c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('duration')
        batch_op.drop_column('xp_score')

    # ### end Alembic commands ###
